=== saborforly/oec-prototype/EvtUtilities/EvtAlgorithms/share/defaultseqlist.dtd
<?xml version="1.0" encoding="UTF-8" ?>
 
<!ELEMENT SEQUENCE_LIST (SEQUENCE)+>
<!ELEMENT SEQUENCE (ESALGORITHM)+>
<!ELEMENT ESALGORITHM EMPTY>

<!ATTLIST SEQUENCE 
    sequence_id   CDATA      #REQUIRED
    input         CDATA      #IMPLIED
    output        CDATA      #IMPLIED >

<!ATTLIST ESALGORITHM
    algorithm     CDATA      #REQUIRED
    input         CDATA      #IMPLIED
    output        CDATA      #IMPLIED >

=== saborforly/oec-prototype/EvtUtilities/EvtAlgorithms/share/defaultseqlist.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>

<!DOCTYPE SEQUENCE_LIST SYSTEM "defaultseqlist.dtd">

<SEQUENCE_LIST>
  <SEQUENCE sequence_id="HIT">
    <ESALGORITHM algorithm="EFDetectorHits" />
  </SEQUENCE>

  <SEQUENCE sequence_id="EMC">
    <ESALGORITHM algorithm="EFGlobalEnergy" />
  </SEQUENCE>

  <SEQUENCE sequence_id="CST">
    <ESALGORITHM algorithm="EmcRec" />
    <ESALGORITHM algorithm="EFProcessCluster" />
  </SEQUENCE>

  <SEQUENCE sequence_id="SEC">
    <ESALGORITHM algorithm="EFSectorHits" />
  </SEQUENCE>

  <SEQUENCE sequence_id="MDC">
    <ESALGORITHM algorithm="MdcFastTrkAlg" />
    <ESALGORITHM algorithm="EFChargedTrack" />
  </SEQUENCE>

  <SEQUENCE sequence_id="TOF">
    <ESALGORITHM algorithm="EFFlightTime" />
  </SEQUENCE>

</SEQUENCE_LIST>
